import 'package:hive_flutter/hive_flutter.dart';
import 'package:ledger/models/word_model.dart';

class StorageService {
  static const String wordBoxName = 'words_box';
  static const String collectionsBoxName = 'collections_box';

  Future<void> init() async {
    await Hive.initFlutter();
    
    // Adapters will be generated by build_runner. 
    // We need to register them here.
    // Note: If generated code isn't ready, this might show errors in IDE but logic is correct.
    Hive.registerAdapter(WordAdapter());
    Hive.registerAdapter(MeaningAdapter());
    Hive.registerAdapter(DefinitionAdapter());

    await Hive.openBox<Word>(wordBoxName);
    // await Hive.openBox<String>(collectionsBoxName); // For sets names or complex objects
  }

  Box<Word> get wordBox => Hive.box<Word>(wordBoxName);

  Future<void> saveWord(Word word) async {
    // Save word using the word itself as key for easy lookup
    await wordBox.put(word.word.toLowerCase(), word);
  }

  Word? getWord(String word) {
    return wordBox.get(word.toLowerCase());
  }

  Future<void> deleteWord(String word) async {
    await wordBox.delete(word.toLowerCase());
  }

  List<Word> getRecentWords() {
    return wordBox.values.toList().reversed.toList();
    // In a real app, implementing proper recent logic might rely on the lastReviewDate
  }
}
